"""
LawForge Phase IV: Circuit Breaker Export
==========================================
Generates self-defending FAISS client code that automatically:
- Reduces nprobe when hazard exceeds threshold
- Switches to lower-accuracy mode under stress
- Logs all interventions
- Resumes optimal mode when safe

This is RUNNABLE CODE, not pseudocode.
"""

import logging
import time
from typing import Optional, Dict, Any
from dataclasses import dataclass, field
from enum import Enum
import json

logger = logging.getLogger("lawforge.circuit_breaker")


class CircuitState(str, Enum):
    """Circuit breaker states."""
    CLOSED = "closed"  # Normal operation
    OPEN = "open"      # Degraded mode active
    HALF_OPEN = "half_open"  # Testing recovery


@dataclass
class CircuitBreakerConfig:
    """Configuration for the circuit breaker."""
    # Thresholds
    recall_threshold: float = 0.7  # Below this, trigger degraded mode
    latency_threshold_ms: float = 50.0  # Above this, trigger degraded mode
    hazard_threshold: float = 0.6  # Forecast hazard score threshold
    
    # Recovery
    recovery_check_interval_s: float = 30.0  # How often to check for recovery
    consecutive_successes_for_close: int = 3  # Successes needed to close circuit
    
    # Degraded mode settings
    degraded_nprobe: int = 1  # Minimum nprobe in degraded mode
    degraded_ef_search: int = 16  # Reduced ef_search for HNSW
    
    # Normal mode settings
    optimal_nprobe: int = 10
    optimal_ef_search: int = 64


@dataclass
class CircuitBreakerState:
    """Current state of the circuit breaker."""
    state: CircuitState = CircuitState.CLOSED
    consecutive_successes: int = 0
    consecutive_failures: int = 0
    last_state_change: float = 0.0
    total_interventions: int = 0
    interventions_log: list = field(default_factory=list)


def generate_circuit_breaker_code(config: CircuitBreakerConfig) -> str:
    """
    Generate Python code for a self-defending FAISS client.
    
    This generates RUNNABLE code that can be saved and executed.
    """
    code = f'''"""
LawForge Self-Defending FAISS Client
=====================================
Auto-generated circuit breaker for FAISS index operations.

Generated by LawForge Phase IV
Configuration:
- Recall Threshold: {config.recall_threshold}
- Latency Threshold: {config.latency_threshold_ms}ms
- Hazard Threshold: {config.hazard_threshold}

Behavior:
- Automatically reduces nprobe when hazard exceeds threshold
- Switches to lower-accuracy mode under stress
- Logs all interventions
- Resumes optimal mode when safe
"""

import logging
import time
from typing import Optional, Dict, Any, List, Tuple
from dataclasses import dataclass, field
from enum import Enum
import numpy as np

try:
    import faiss
    FAISS_AVAILABLE = True
except ImportError:
    FAISS_AVAILABLE = False
    faiss = None

logger = logging.getLogger("lawforge.self_defending_client")


class CircuitState(str, Enum):
    """Circuit breaker states."""
    CLOSED = "closed"      # Normal operation - optimal settings
    OPEN = "open"          # Degraded mode - reduced accuracy for stability
    HALF_OPEN = "half_open"  # Testing recovery - cautiously returning to normal


@dataclass
class Intervention:
    """Record of a circuit breaker intervention."""
    timestamp: float
    previous_state: str
    new_state: str
    trigger: str
    metrics: Dict[str, float]
    action_taken: str


@dataclass
class ClientConfig:
    """Configuration for the self-defending client."""
    # Thresholds (from LawForge calibration)
    recall_threshold: float = {config.recall_threshold}
    latency_threshold_ms: float = {config.latency_threshold_ms}
    hazard_threshold: float = {config.hazard_threshold}
    
    # Recovery settings
    recovery_check_interval_s: float = {config.recovery_check_interval_s}
    consecutive_successes_for_close: int = {config.consecutive_successes_for_close}
    
    # Degraded mode settings (from LawForge safe operating zones)
    degraded_nprobe: int = {config.degraded_nprobe}
    degraded_ef_search: int = {config.degraded_ef_search}
    
    # Optimal mode settings
    optimal_nprobe: int = {config.optimal_nprobe}
    optimal_ef_search: int = {config.optimal_ef_search}


class SelfDefendingFAISSClient:
    """
    Self-defending FAISS client with automatic circuit breaker.
    
    This client automatically degrades performance to maintain stability
    when it detects approaching failure boundaries.
    
    Usage:
        client = SelfDefendingFAISSClient(index, config)
        results = client.search(queries, k=10)
        
        # The client automatically:
        # - Monitors recall and latency
        # - Reduces accuracy settings under stress
        # - Logs all interventions
        # - Recovers to optimal mode when safe
    """
    
    def __init__(
        self, 
        index: "faiss.Index",
        config: Optional[ClientConfig] = None,
        dimensions: int = 128
    ):
        self.index = index
        self.config = config or ClientConfig()
        self.dimensions = dimensions
        
        # Circuit breaker state
        self.state = CircuitState.CLOSED
        self.consecutive_successes = 0
        self.consecutive_failures = 0
        self.last_state_change = time.time()
        self.last_recovery_check = time.time()
        
        # Intervention history
        self.interventions: List[Intervention] = []
        self.total_interventions = 0
        
        # Metrics tracking
        self.recent_recalls: List[float] = []
        self.recent_latencies: List[float] = []
        self.metrics_window = 10  # Track last N queries
        
        # Ground truth index for recall measurement
        self._ground_truth_index: Optional["faiss.Index"] = None
        
        logger.info(f"Initialized SelfDefendingFAISSClient in {{self.state.value}} state")
    
    def _log_intervention(
        self, 
        previous_state: CircuitState,
        new_state: CircuitState,
        trigger: str,
        metrics: Dict[str, float],
        action: str
    ) -> None:
        """Log a circuit breaker intervention."""
        intervention = Intervention(
            timestamp=time.time(),
            previous_state=previous_state.value,
            new_state=new_state.value,
            trigger=trigger,
            metrics=metrics,
            action_taken=action
        )
        self.interventions.append(intervention)
        self.total_interventions += 1
        
        logger.warning(
            f"CIRCUIT BREAKER INTERVENTION: {{previous_state.value}} -> {{new_state.value}} | "
            f"Trigger: {{trigger}} | Action: {{action}}"
        )
    
    def _calculate_hazard_score(self) -> float:
        """
        Calculate current hazard score based on recent metrics.
        
        Hazard = weighted combination of recall degradation and latency increase.
        """
        if len(self.recent_recalls) < 2:
            return 0.0
        
        # Recall component: how close to threshold
        avg_recall = sum(self.recent_recalls[-5:]) / min(5, len(self.recent_recalls))
        recall_margin = (avg_recall - self.config.recall_threshold)
        recall_hazard = max(0, 1 - (recall_margin / 0.3))  # 0.3 = safe margin
        
        # Latency component: how close to threshold
        avg_latency = sum(self.recent_latencies[-5:]) / min(5, len(self.recent_latencies))
        latency_margin = (self.config.latency_threshold_ms - avg_latency)
        latency_hazard = max(0, 1 - (latency_margin / 20))  # 20ms = safe margin
        
        # Combined hazard (weighted)
        hazard = 0.6 * recall_hazard + 0.4 * latency_hazard
        return min(1.0, hazard)
    
    def _apply_degraded_mode(self) -> str:
        """Apply degraded mode settings to the index."""
        actions = []
        
        if hasattr(self.index, 'nprobe'):
            self.index.nprobe = self.config.degraded_nprobe
            actions.append(f"nprobe={{self.config.degraded_nprobe}}")
        
        if hasattr(self.index, 'hnsw'):
            self.index.hnsw.efSearch = self.config.degraded_ef_search
            actions.append(f"efSearch={{self.config.degraded_ef_search}}")
        
        return ", ".join(actions) if actions else "no parameters adjusted"
    
    def _apply_optimal_mode(self) -> str:
        """Apply optimal mode settings to the index."""
        actions = []
        
        if hasattr(self.index, 'nprobe'):
            self.index.nprobe = self.config.optimal_nprobe
            actions.append(f"nprobe={{self.config.optimal_nprobe}}")
        
        if hasattr(self.index, 'hnsw'):
            self.index.hnsw.efSearch = self.config.optimal_ef_search
            actions.append(f"efSearch={{self.config.optimal_ef_search}}")
        
        return ", ".join(actions) if actions else "no parameters adjusted"
    
    def _check_and_update_state(self, recall: float, latency_ms: float) -> None:
        """Check metrics and update circuit breaker state if needed."""
        current_time = time.time()
        metrics = {{"recall": recall, "latency_ms": latency_ms}}
        
        # Calculate hazard
        hazard = self._calculate_hazard_score()
        metrics["hazard"] = hazard
        
        # Determine if this query was successful (within bounds)
        query_success = recall >= self.config.recall_threshold and latency_ms <= self.config.latency_threshold_ms
        
        if self.state == CircuitState.CLOSED:
            # Normal operation - check for degradation
            if hazard >= self.config.hazard_threshold:
                # Transition to OPEN (degraded mode)
                action = self._apply_degraded_mode()
                self._log_intervention(
                    CircuitState.CLOSED,
                    CircuitState.OPEN,
                    f"Hazard score {{hazard:.3f}} exceeded threshold {{self.config.hazard_threshold}}",
                    metrics,
                    f"Entering degraded mode: {{action}}"
                )
                self.state = CircuitState.OPEN
                self.last_state_change = current_time
                self.consecutive_successes = 0
                self.consecutive_failures = 0
            elif not query_success:
                self.consecutive_failures += 1
                self.consecutive_successes = 0
                
                if self.consecutive_failures >= 3:
                    # Emergency degradation
                    action = self._apply_degraded_mode()
                    self._log_intervention(
                        CircuitState.CLOSED,
                        CircuitState.OPEN,
                        f"Consecutive failures ({{self.consecutive_failures}})",
                        metrics,
                        f"Emergency degradation: {{action}}"
                    )
                    self.state = CircuitState.OPEN
                    self.last_state_change = current_time
                    self.consecutive_failures = 0
            else:
                self.consecutive_successes += 1
                self.consecutive_failures = 0
        
        elif self.state == CircuitState.OPEN:
            # Degraded mode - check for recovery opportunity
            time_since_change = current_time - self.last_state_change
            
            if time_since_change >= self.config.recovery_check_interval_s:
                # Time to check if we can start recovering
                if hazard < self.config.hazard_threshold * 0.7:  # Hysteresis
                    # Transition to HALF_OPEN (testing recovery)
                    self._log_intervention(
                        CircuitState.OPEN,
                        CircuitState.HALF_OPEN,
                        f"Hazard reduced to {{hazard:.3f}}, testing recovery",
                        metrics,
                        "Entering half-open state for recovery testing"
                    )
                    self.state = CircuitState.HALF_OPEN
                    self.last_state_change = current_time
                    self.consecutive_successes = 0
        
        elif self.state == CircuitState.HALF_OPEN:
            # Testing recovery - cautiously returning to normal
            if query_success and hazard < self.config.hazard_threshold * 0.7:
                self.consecutive_successes += 1
                self.consecutive_failures = 0
                
                if self.consecutive_successes >= self.config.consecutive_successes_for_close:
                    # Recovery successful - transition to CLOSED
                    action = self._apply_optimal_mode()
                    self._log_intervention(
                        CircuitState.HALF_OPEN,
                        CircuitState.CLOSED,
                        f"Recovery successful after {{self.consecutive_successes}} successes",
                        metrics,
                        f"Resuming optimal mode: {{action}}"
                    )
                    self.state = CircuitState.CLOSED
                    self.last_state_change = current_time
                    self.consecutive_successes = 0
            else:
                # Recovery failed - back to OPEN
                self.consecutive_failures += 1
                self.consecutive_successes = 0
                
                action = self._apply_degraded_mode()
                self._log_intervention(
                    CircuitState.HALF_OPEN,
                    CircuitState.OPEN,
                    f"Recovery failed (hazard={{hazard:.3f}}, success={{query_success}})",
                    metrics,
                    f"Returning to degraded mode: {{action}}"
                )
                self.state = CircuitState.OPEN
                self.last_state_change = current_time
                self.consecutive_failures = 0
    
    def search(
        self, 
        queries: np.ndarray, 
        k: int = 10,
        measure_recall: bool = False
    ) -> Tuple[np.ndarray, np.ndarray]:
        """
        Search the index with automatic circuit breaker protection.
        
        Args:
            queries: Query vectors (n_queries x dimensions)
            k: Number of neighbors to return
            measure_recall: If True, compute recall against brute-force (expensive)
        
        Returns:
            Tuple of (distances, indices)
        """
        if not FAISS_AVAILABLE or self.index is None:
            raise RuntimeError("FAISS index not available")
        
        n_queries = queries.shape[0]
        
        # Execute search with timing
        start_time = time.perf_counter()
        D, I = self.index.search(queries, k)
        latency_ms = (time.perf_counter() - start_time) * 1000 / n_queries
        
        # Measure recall if requested (expensive - for monitoring only)
        recall = 1.0
        if measure_recall and self._ground_truth_index is not None:
            _, gt_I = self._ground_truth_index.search(queries, k)
            correct = 0
            for i in range(n_queries):
                correct += len(set(I[i]).intersection(set(gt_I[i])))
            recall = correct / (n_queries * k)
        
        # Track metrics
        self.recent_recalls.append(recall)
        self.recent_latencies.append(latency_ms)
        
        # Keep only recent history
        if len(self.recent_recalls) > self.metrics_window:
            self.recent_recalls = self.recent_recalls[-self.metrics_window:]
            self.recent_latencies = self.recent_latencies[-self.metrics_window:]
        
        # Update circuit breaker state
        self._check_and_update_state(recall, latency_ms)
        
        return D, I
    
    def set_ground_truth_index(self, index: "faiss.Index") -> None:
        """Set a ground truth index for recall measurement."""
        self._ground_truth_index = index
    
    def get_state(self) -> Dict[str, Any]:
        """Get current circuit breaker state."""
        return {{
            "state": self.state.value,
            "consecutive_successes": self.consecutive_successes,
            "consecutive_failures": self.consecutive_failures,
            "total_interventions": self.total_interventions,
            "recent_avg_recall": sum(self.recent_recalls[-5:]) / max(1, min(5, len(self.recent_recalls))),
            "recent_avg_latency_ms": sum(self.recent_latencies[-5:]) / max(1, min(5, len(self.recent_latencies))),
            "hazard_score": self._calculate_hazard_score()
        }}
    
    def get_interventions_log(self) -> List[Dict[str, Any]]:
        """Get log of all interventions."""
        return [
            {{
                "timestamp": i.timestamp,
                "previous_state": i.previous_state,
                "new_state": i.new_state,
                "trigger": i.trigger,
                "metrics": i.metrics,
                "action_taken": i.action_taken
            }}
            for i in self.interventions
        ]
    
    def reset_circuit_breaker(self) -> None:
        """Reset circuit breaker to initial state."""
        self.state = CircuitState.CLOSED
        self.consecutive_successes = 0
        self.consecutive_failures = 0
        self.last_state_change = time.time()
        self._apply_optimal_mode()
        logger.info("Circuit breaker reset to CLOSED state")


# Example usage
if __name__ == "__main__":
    import logging
    logging.basicConfig(level=logging.INFO)
    
    # This is example code - replace with your actual FAISS setup
    if FAISS_AVAILABLE:
        # Create a sample index
        d = 128
        n = 10000
        vectors = np.random.random((n, d)).astype('float32')
        
        # Create IVF index
        nlist = 100
        quantizer = faiss.IndexFlatL2(d)
        index = faiss.IndexIVFFlat(quantizer, d, nlist)
        index.train(vectors)
        index.add(vectors)
        
        # Create self-defending client
        config = ClientConfig()
        client = SelfDefendingFAISSClient(index, config, dimensions=d)
        
        # Optional: Set ground truth for recall measurement
        flat_index = faiss.IndexFlatL2(d)
        flat_index.add(vectors)
        client.set_ground_truth_index(flat_index)
        
        # Run queries
        print("Running queries with circuit breaker protection...")
        for i in range(10):
            queries = np.random.random((10, d)).astype('float32')
            D, I = client.search(queries, k=10, measure_recall=True)
            
            state = client.get_state()
            print(f"Query batch {{i+1}}: state={{state['state']}}, hazard={{state['hazard_score']:.3f}}")
        
        # Print intervention log
        print("\\nIntervention Log:")
        for intervention in client.get_interventions_log():
            print(f"  {{intervention['timestamp']:.2f}}: {{intervention['previous_state']}} -> {{intervention['new_state']}}")
            print(f"    Trigger: {{intervention['trigger']}}")
            print(f"    Action: {{intervention['action_taken']}}")
    else:
        print("FAISS not available - cannot run example")
'''
    return code


def generate_circuit_breaker_readme() -> str:
    """Generate README for the circuit breaker export."""
    return """# LawForge Self-Defending FAISS Client

> Generated by LawForge Phase IV Circuit Breaker Export

## Overview

This is a **self-defending FAISS client** that automatically protects your search infrastructure from performance degradation and failures.

## Key Features

### Automatic Protection
- **Hazard Monitoring**: Continuously monitors recall and latency metrics
- **Predictive Degradation**: Enters degraded mode BEFORE failures occur
- **Automatic Recovery**: Returns to optimal mode when conditions improve

### Circuit Breaker States

| State | Description | Behavior |
|-------|-------------|----------|
| 🟢 CLOSED | Normal operation | Optimal nprobe/efSearch settings |
| 🔴 OPEN | Degraded mode | Reduced accuracy, guaranteed stability |
| 🟡 HALF_OPEN | Recovery testing | Cautiously returning to normal |

### Interventions

The client logs all interventions with:
- Timestamp
- Trigger reason
- Metrics at time of intervention
- Action taken

## Usage

```python
from self_defending_faiss import SelfDefendingFAISSClient, ClientConfig

# Create your FAISS index as usual
index = faiss.IndexIVFFlat(quantizer, d, nlist)
index.train(vectors)
index.add(vectors)

# Wrap with self-defending client
config = ClientConfig()
client = SelfDefendingFAISSClient(index, config)

# Use normally - protection is automatic
D, I = client.search(queries, k=10)

# Check state
state = client.get_state()
print(f"State: {state['state']}, Hazard: {state['hazard_score']:.2f}")

# Get intervention history
for intervention in client.get_interventions_log():
    print(intervention)
```

## Configuration

| Parameter | Default | Description |
|-----------|---------|-------------|
| recall_threshold | 0.7 | Below this, trigger degraded mode |
| latency_threshold_ms | 50.0 | Above this, trigger degraded mode |
| hazard_threshold | 0.6 | Forecast hazard score threshold |
| recovery_check_interval_s | 30.0 | How often to check for recovery |
| consecutive_successes_for_close | 3 | Successes needed to close circuit |
| degraded_nprobe | 1 | Minimum nprobe in degraded mode |
| optimal_nprobe | 10 | Normal operation nprobe |

## Guiding Principle

> LawForge does not optimize systems.
> It prevents engineers from unknowingly driving them off cliffs.

---

*Generated by LawForge Phase IV*
"""


def export_circuit_breaker(
    config: CircuitBreakerConfig,
    output_dir: str = "."
) -> Dict[str, str]:
    """
    Export complete circuit breaker package.
    
    Returns dict of filename -> content.
    """
    return {
        "self_defending_faiss.py": generate_circuit_breaker_code(config),
        "README_CIRCUIT_BREAKER.md": generate_circuit_breaker_readme(),
        "circuit_breaker_config.json": json.dumps({
            "recall_threshold": config.recall_threshold,
            "latency_threshold_ms": config.latency_threshold_ms,
            "hazard_threshold": config.hazard_threshold,
            "recovery_check_interval_s": config.recovery_check_interval_s,
            "consecutive_successes_for_close": config.consecutive_successes_for_close,
            "degraded_nprobe": config.degraded_nprobe,
            "degraded_ef_search": config.degraded_ef_search,
            "optimal_nprobe": config.optimal_nprobe,
            "optimal_ef_search": config.optimal_ef_search
        }, indent=2)
    }


if __name__ == "__main__":
    # Example export
    config = CircuitBreakerConfig()
    exports = export_circuit_breaker(config)
    
    for filename, content in exports.items():
        print(f"\n{'='*60}")
        print(f"FILE: {filename}")
        print('='*60)
        print(content[:500] + "..." if len(content) > 500 else content)
