import { SOSGenome } from "../types";

const getTimestamp = () => new Date().toISOString();

export const generateReadme = (genomes: Record<string, SOSGenome>): string => {
  const domainsList = Object.keys(genomes).map(k => 
    `- ${k.toUpperCase()} (Alpha: ${genomes[k].alpha.toFixed(2)}, Strategy: ${genomes[k].sampleStrategy})`
  ).join('\n');

  return `# SOS Evolution - Production Export
Generated: ${getTimestamp()}

This is a self-optimizing inference API generated from the SOS Dashboard.
It contains the evolved strategies for the following domains:
${domainsList}

## 🚀 Quick Start

### 1. Create Project Structure
\`\`\`bash
mkdir -p optimizers
# Copy main.py to root
# Copy each domain optimizer to optimizers/
# Copy requirements.txt and Dockerfile
\`\`\`

### 2. Install Dependencies
\`\`\`bash
pip install -r requirements.txt
\`\`\`

### 3. Run the Server
\`\`\`bash
uvicorn main:app --reload --host 0.0.0.0 --port 8000
\`\`\`

### 4. Docker Deployment
\`\`\`bash
docker build -t sos-optimizer .
docker run -p 8000:8000 sos-optimizer
\`\`\`

## 🔌 API Endpoints

- \`POST /v1/optimize\`: Get optimal parameters for a domain context.
- \`GET /health\`: System status.

## 📁 Project Structure
\`\`\`
sos-optimizer/
├── main.py              # FastAPI application
├── requirements.txt     # Python dependencies
├── Dockerfile           # Container configuration
├── README.md            # This file
└── optimizers/          # Domain optimizers
    ├── __init__.py      # Package init
${Object.keys(genomes).map(k => `    ├── ${k}.py           # ${k.toUpperCase()} optimizer`).join('\n')}
\`\`\`

## 🧪 Example Usage

\`\`\`bash
# Health check
curl http://localhost:8000/health

# Optimize for a domain
curl -X POST http://localhost:8000/v1/optimize \\
  -H "Content-Type: application/json" \\
  -d '{"domain": "faiss", "context_vector": [0.5, 0.3, 0.2]}'
\`\`\`
`;
};

export const generateDockerfile = (): string => {
  return `# Generated by SOS Dashboard
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc && \\
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port
EXPOSE 8000

# Run application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
};

export const generateOptimizersInit = (genomes: Record<string, SOSGenome>): string => {
  const imports = Object.keys(genomes).map(d => 
    `from .${d} import ${d.charAt(0).toUpperCase() + d.slice(1)}Optimizer`
  ).join('\n');

  const allExports = Object.keys(genomes).map(d => 
    `    "${d.charAt(0).toUpperCase() + d.slice(1)}Optimizer"`
  ).join(',\n');

  return `"""
SOS Optimizers Package
Generated: ${getTimestamp()}

This package contains domain-specific optimizers evolved by the SOS Dashboard.
"""

${imports}

__all__ = [
${allExports}
]
`;
};

export const generateOptimizerCode = (genome: SOSGenome): string => {
  const strategyLogic: Record<string, string> = {
    uniform: "return np.random.uniform(low=0.0, high=1.0, size=(n_candidates, dim))",
    gaussian: "return np.random.normal(loc=0.5, scale=0.2, size=(n_candidates, dim))",
    adaptive: "return (np.random.normal(0.5, 0.1, size=(n_candidates, dim)) + np.random.uniform(0, 1, size=(n_candidates, dim))) / 2",
    exploit: "return np.random.normal(loc=0.5, scale=0.05, size=(n_candidates, dim))"
  };

  const className = genome.domain.charAt(0).toUpperCase() + genome.domain.slice(1) + "Optimizer";
  const strategy = strategyLogic[genome.sampleStrategy] || strategyLogic['uniform'];

  return `"""
Domain: ${genome.domain.toUpperCase()}
Generated Strategy: ${genome.sampleStrategy}
Alpha Parameter: ${genome.alpha.toFixed(4)}
Fitness Snapshot: ${genome.fitness.toFixed(4)}

Generated by SOS Dashboard
"""
import numpy as np
import logging
from typing import List, Dict, Any

from pydantic import BaseModel, Field


logger = logging.getLogger("sos.${genome.domain}")


class OptimizerConfig(BaseModel):
    """Configuration for the ${genome.domain} optimizer."""
    alpha: float = Field(default=${genome.alpha.toFixed(4)}, description="P(valid) exponent bias")
    strategy: str = Field(default="${genome.sampleStrategy}", description="Sampling strategy")
    exploration_bonus: float = Field(default=${genome.explorationBonus.toFixed(4)}, description="Exploration bonus")


class ${className}:
    """
    ${genome.domain.toUpperCase()} Domain Optimizer
    
    Evolved parameters:
    - Alpha: ${genome.alpha.toFixed(4)}
    - Strategy: ${genome.sampleStrategy}
    - Fitness: ${genome.fitness.toFixed(4)}
    """
    
    def __init__(self):
        self.config = OptimizerConfig()
        # Initialize simplified surrogate weights (simulating the trained model state)
        self.surrogate_weights = np.random.randn(10) * 0.1
        logger.info("Initialized ${genome.domain} optimizer with alpha=%s", self.config.alpha)

    def propose_parameters(
        self, 
        context_vector: List[float], 
        n_candidates: int = 50
    ) -> Dict[str, Any]:
        """
        Proposes optimal parameters based on the evolved strategy.
        
        Args:
            context_vector: Input context for optimization
            n_candidates: Number of candidates to generate
            
        Returns:
            Dictionary with parameters, confidence, and strategy used
        """
        try:
            dim = len(context_vector) if context_vector else 5
            
            # 1. Generate Candidates using Evolved Strategy
            candidates = self._generate_candidates(n_candidates, dim)
            
            # 2. Score Candidates using Evolved Alpha
            # Score = E[Reward] * P(Feasible)^alpha
            scores = self._score_candidates(candidates)
            
            # 3. Select Best
            best_idx = int(np.argmax(scores))
            best_params = candidates[best_idx].tolist()
            
            return {
                "parameters": best_params,
                "confidence": float(scores[best_idx]),
                "strategy_used": self.config.strategy
            }
        except Exception as e:
            logger.error("Optimization failed: %s", str(e))
            # Fallback safe parameters
            return {"parameters": [0.5] * 5, "error": str(e)}

    def _generate_candidates(self, n_candidates: int, dim: int) -> np.ndarray:
        """Generate candidate parameters using evolved strategy: ${genome.sampleStrategy}"""
        ${strategy}

    def _score_candidates(self, candidates: np.ndarray) -> np.ndarray:
        """
        Score candidate parameters.
        
        In a real deployed version, this would use the loaded surrogate model.
        """
        # P(Feasible) proxy
        feasibility = 1.0 / (1.0 + np.exp(-np.mean(candidates, axis=1)))
        
        # E[Reward] proxy
        reward = np.abs(np.sin(np.sum(candidates, axis=1)))
        
        # The Secret Sauce: Alpha
        return reward * (feasibility ** self.config.alpha) + self.config.exploration_bonus
`;
};

export const generateMain = (genomes: Record<string, SOSGenome>): string => {
  const imports = Object.keys(genomes)
    .map(d => `from optimizers.${d} import ${d.charAt(0).toUpperCase() + d.slice(1)}Optimizer`)
    .join('\n    ');

  const registryInit = Object.keys(genomes)
    .map(d => `        "${d}": ${d.charAt(0).toUpperCase() + d.slice(1)}Optimizer(),`)
    .join('\n');

  const classNames = Object.keys(genomes)
    .map(d => `${d.charAt(0).toUpperCase() + d.slice(1)}Optimizer`)
    .join(', ');

  return `"""
SOS Evolution API - Production Server
Generated by SOS Dashboard

This is a self-optimizing inference API with evolved domain optimizers.
"""
import logging
import time
from typing import List, Dict, Any
from contextlib import asynccontextmanager

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel


# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s - %(name)s - %(levelname)s - %(message)s"
)
logger = logging.getLogger("sos.main")


# Import Evolved Optimizers
try:
    ${imports}
    OPTIMIZERS_AVAILABLE = True
except ImportError as e:
    logger.warning("Failed to import optimizers: %s", e)
    logger.warning("Running in standalone mode - no optimizers available")
    OPTIMIZERS_AVAILABLE = False


# --- Data Models ---
class OptimizationRequest(BaseModel):
    """Request model for optimization endpoint."""
    domain: str
    context_vector: List[float] = []
    constraints: Dict[str, Any] = {}


class OptimizationResponse(BaseModel):
    """Response model for optimization endpoint."""
    domain: str
    parameters: Any
    meta: Dict[str, Any]


# --- Registry ---
def initialize_registry() -> Dict[str, Any]:
    """Initialize the optimizer registry."""
    if not OPTIMIZERS_AVAILABLE:
        return {}
    
    try:
        return {
${registryInit}
        }
    except Exception as e:
        logger.error("Failed to initialize optimizers: %s", e)
        return {}


# --- Application Lifecycle ---
@asynccontextmanager
async def lifespan(app: FastAPI):
    """Application lifecycle manager."""
    logger.info("SOS Evolution API starting up...")
    app.state.registry = initialize_registry()
    logger.info("Loaded %d domain optimizers", len(app.state.registry))
    yield
    logger.info("SOS Evolution API shutting down...")


# --- FastAPI Application ---
app = FastAPI(
    title="SOS Evolution API",
    version="2.0.0",
    description="Self-Optimizing Software Interface - Evolved Optimizers",
    lifespan=lifespan
)


@app.get("/health")
async def health_check():
    """Health check endpoint."""
    registry = getattr(app.state, "registry", {})
    return {
        "status": "healthy",
        "active_domains": list(registry.keys()),
        "optimizers_count": len(registry)
    }


@app.post("/v1/optimize", response_model=OptimizationResponse)
async def optimize(request: OptimizationRequest):
    """
    Route request to the specific domain optimizer evolved by the SOS system.
    
    Args:
        request: Optimization request with domain and context
        
    Returns:
        Optimized parameters with metadata
    """
    registry = getattr(app.state, "registry", {})
    
    if request.domain not in registry:
        available = list(registry.keys())
        raise HTTPException(
            status_code=404,
            detail=f"Domain '{request.domain}' not found. Available: {available}"
        )
    
    start_ts = time.time()
    optimizer = registry[request.domain]
    
    try:
        result = optimizer.propose_parameters(
            context_vector=request.context_vector,
            n_candidates=100
        )
        
        inference_time = (time.time() - start_ts) * 1000
        
        return {
            "domain": request.domain,
            "parameters": result["parameters"],
            "meta": {
                "strategy": result.get("strategy_used", "unknown"),
                "confidence": result.get("confidence", 0.0),
                "inference_ms": round(inference_time, 2),
                "alpha_version": optimizer.config.alpha
            }
        }
    except Exception as e:
        logger.error("Optimization error in %s: %s", request.domain, e)
        raise HTTPException(status_code=500, detail="Internal Optimization Error")


if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
`;
};

export const generateRequirements = (): string => {
  return `fastapi>=0.109.0
uvicorn[standard]>=0.27.0
numpy>=1.26.0
pydantic>=2.6.0
scikit-learn>=1.4.0
python-multipart>=0.0.9
`;
};
