import { SOSGenome } from "../types";

const getTimestamp = () => new Date().toISOString();

export const generateReadme = (genomes: Record<string, SOSGenome>): string => {
  return `# SOS Evolution - Production Export
Generated: ${getTimestamp()}

This is a self-optimizing inference API generated from the SOS Dashboard.
It contains the evolved strategies for the following domains:
${Object.keys(genomes).map(k => `- ${k.toUpperCase()} (Alpha: ${genomes[k].alpha.toFixed(2)}, Strategy: ${genomes[k].sampleStrategy})`).join('\n')}

## 🚀 Quick Start

### 1. Install Dependencies
\`\`\`bash
pip install -r requirements.txt
\`\`\`

### 2. Run the Server
\`\`\`bash
uvicorn main:app --reload --host 0.0.0.0 --port 8000
\`\`\`

### 3. Docker Deployment
\`\`\`bash
docker build -t sos-optimizer .
docker run -p 8000:8000 sos-optimizer
\`\`\`

## 🔌 API Endpoints

- \`POST /v1/optimize\`: Get optimal parameters for a domain context.
- \`GET /health\`: System status.
`;
};

export const generateDockerfile = (): string => {
  return `# Generated by SOS
FROM python:3.11-slim

WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y --no-install-recommends gcc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application code
COPY . .

# Expose port
EXPOSE 8000

# Run application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
`;
};

export const generateOptimizerCode = (genome: SOSGenome): string => {
  const strategyLogic = {
    uniform: "return np.random.uniform(low=0.0, high=1.0, size=(n_candidates, dim))",
    gaussian: "return np.random.normal(loc=0.5, scale=0.2, size=(n_candidates, dim))",
    adaptive: "return (np.random.normal(0.5, 0.1, size=(n_candidates, dim)) + np.random.uniform(0,1, size=(n_candidates, dim))) / 2",
    exploit: "return np.random.normal(loc=0.5, scale=0.05, size=(n_candidates, dim)) # Tight variance"
  };

  return `"""
Domain: ${genome.domain.toUpperCase()}
Generated Strategy: ${genome.sampleStrategy}
Alpha Parameter: ${genome.alpha.toFixed(4)}
Fitness Snapshot: ${genome.fitness.toFixed(4)}
"""
import numpy as np
import logging
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

logger = logging.getLogger("sos.${genome.domain}")

class OptimizerConfig(BaseModel):
    alpha: float = Field(default=${genome.alpha.toFixed(4)}, description="P(valid) exponent bias")
    strategy: str = Field(default="${genome.sampleStrategy}", description="Sampling strategy")
    exploration_bonus: float = ${genome.explorationBonus.toFixed(4)}

class ${genome.domain.charAt(0).toUpperCase() + genome.domain.slice(1)}Optimizer:
    def __init__(self):
        self.config = OptimizerConfig()
        # Initialize simplified surrogate weights (simulating the trained model state)
        self.surrogate_weights = np.random.randn(10) * 0.1
        logger.info(f"Initialized {genome.domain} optimizer with alpha={self.config.alpha}")

    def propose_parameters(self, context_vector: List[float], n_candidates: int = 50) -> Dict[str, Any]:
        """
        Proposes optimal parameters based on the evolved strategy.
        """
        try:
            dim = len(context_vector) if context_vector else 5
            
            # 1. Generate Candidates using Evolved Strategy
            candidates = self._generate_candidates(n_candidates, dim)
            
            # 2. Score Candidates using Evolved Alpha
            # Score = E[Reward] * P(Feasible)^alpha
            scores = self._score_candidates(candidates)
            
            # 3. Select Best
            best_idx = np.argmax(scores)
            best_params = candidates[best_idx].tolist()
            
            return {
                "parameters": best_params,
                "confidence": float(scores[best_idx]),
                "strategy_used": self.config.strategy
            }
        except Exception as e:
            logger.error(f"Optimization failed: {str(e)}")
            # Fallback safe parameters
            return {"parameters": [0.5] * 5, "error": str(e)}

    def _generate_candidates(self, n_candidates: int, dim: int) -> np.ndarray:
        # Strategy: ${genome.sampleStrategy}
        ${strategyLogic[genome.sampleStrategy] || strategyLogic['uniform']}

    def _score_candidates(self, candidates: np.ndarray) -> np.ndarray:
        # Mock surrogate scoring for demonstration
        # In a real deployed version, this would be the loaded .pkl model
        
        # P(Feasible) proxy
        feasibility = 1.0 / (1.0 + np.exp(-np.mean(candidates, axis=1)))
        
        # E[Reward] proxy
        reward = np.abs(np.sin(np.sum(candidates, axis=1)))
        
        # The Secret Sauce: Alpha
        return reward * (feasibility ** self.config.alpha) + self.config.exploration_bonus
`;
};

export const generateMain = (genomes: Record<string, SOSGenome>): string => {
  const imports = Object.keys(genomes)
    .map(d => `from optimizers.${d} import ${d.charAt(0).toUpperCase() + d.slice(1)}Optimizer`)
    .join('\n');

  const registryInit = Object.keys(genomes)
    .map(d => `    "${d}": ${d.charAt(0).toUpperCase() + d.slice(1)}Optimizer(),`)
    .join('\n');

  return `import logging
import time
from typing import List, Dict, Any, Optional
from fastapi import FastAPI, HTTPException, BackgroundTasks
from pydantic import BaseModel
from contextlib import asynccontextmanager

# Configure Logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger("sos.main")

# Import Evolved Optimizers
try:
${imports}
except ImportError as e:
    logger.error(f"Failed to import optimizers: {e}")
    # Handling for single-file testing context
    pass

# --- Data Models ---
class OptimizationRequest(BaseModel):
    domain: str
    context_vector: List[float] = []
    constraints: Dict[str, Any] = {}

class OptimizationResponse(BaseModel):
    domain: str
    parameters: Any
    meta: Dict[str, Any]

# --- Lifecycle ---
@asynccontextmanager
async def lifespan(app: FastAPI):
    logger.info("SOS Evolution API starting up...")
    # Load specific heavy weights here if needed
    yield
    logger.info("SOS Evolution API shutting down...")

app = FastAPI(
    title="SOS Evolution API", 
    version="2.0.0",
    description="Self-Optimizing Software Interface",
    lifespan=lifespan
)

# Initialize Registry
registry = {}
try:
    registry = {
${registryInit}
    }
except NameError:
    logger.warning("Registry empty due to import errors (running in test mode?)")

@app.get("/health")
async def health_check():
    return {
        "status": "healthy", 
        "active_domains": list(registry.keys()),
        "uptime": "active"
    }

@app.post("/v1/optimize", response_model=OptimizationResponse)
async def optimize(request: OptimizationRequest):
    """
    Route request to the specific domain optimizer evolved by the AI Grower.
    """
    if request.domain not in registry:
        raise HTTPException(
            status_code=404, 
            detail=f"Domain '{request.domain}' not found. Available: {list(registry.keys())}"
        )
    
    start_ts = time.time()
    optimizer = registry[request.domain]
    
    try:
        result = optimizer.propose_parameters(
            context_vector=request.context_vector,
            n_candidates=100
        )
        
        inference_time = (time.time() - start_ts) * 1000
        
        return {
            "domain": request.domain,
            "parameters": result["parameters"],
            "meta": {
                "strategy": result.get("strategy_used", "unknown"),
                "confidence": result.get("confidence", 0.0),
                "inference_ms": round(inference_time, 2),
                "alpha_version": optimizer.config.alpha
            }
        }
    except Exception as e:
        logger.error(f"Optimization error in {request.domain}: {e}")
        raise HTTPException(status_code=500, detail="Internal Optimization Error")

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)
`;
};

export const generateRequirements = (): string => {
  return `fastapi>=0.109.0
uvicorn[standard]>=0.27.0
numpy>=1.26.0
pydantic>=2.6.0
scikit-learn>=1.4.0
python-multipart>=0.0.9
`;
};
